name: DevOps Agent
description: Read-only DevOps observer that summarizes workflow failures and posts a sticky PR comment
author: kumarrajdevops

branding:
  icon: alert-circle
  color: red

inputs:
  token:
    description: "GITHUB_TOKEN for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run devops-agent
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        python "${{ github.action_path }}/agent/gha_pr_comment.py"
